### ISSUE TITLE
Support YAML indents using spaces

### ISSUE THREAD

**Issue by garretwilson** [mickaelistria/eclipse-bluesky#1132] opened 2023-03-16 15:38 UTC
I just installed Eclipse EE 2023-03 on Windows 10.

I have a YAML file. When I indent it uses tabs. How can I specify to indent using two spaces? The preferences for YAML (Wild Web Developer) say nothing about this.

Spaces versus tabs is a fundamental setting for editing any file format. But I want to be able to specify the setting for the format, e.g. the setting for YAML might be different than for XML.

**Comment by garretwilson** [comment] 2023-03-16 15:40
To add insult to injury, the editor is marking the document as having errors, saying:

> Tabs are not allowed as indentation

Yes, YAML forbids tabs, and the new YAML editor seems to have no way to allow spaces when I tab. 🤦

**Comment by angelozerr** [comment] 2023-03-16 17:45
Same issue than for XML https://github.com/eclipse/wildwebdeveloper/issues/872

See my comment https://github.com/eclipse/lemminx/issues/1485#issuecomment-1436492660

**Comment by mickaelistria** [comment] 2023-03-16 19:50
On that particular aspect, if tabs are not allowed for yaml, then the yaml LS should have some onTypeFormatting and formatting configured to replace tabs with spaces.
But indeed, configuring the amount of spaces to insert would still be an issue. Maybe the LS can lookup .editorconfig files to determine that?
Basically, the least we put on client side, and the more we put on LS side, the more value we create as well for other IDEs.

**Comment by garretwilson** [comment] 2023-03-16 20:16
There are few things more basic in an editor than choosing tabs versus spaces. (I'm pretty sure they were doing this 20 years ago, if not 30 years ago.) And if the editor inserts a form of indention that the format doesn't even allow, that pretty much breaks the editor.

Little things like this is why Eclipse is becoming less and less relevant in the modern software development world, and even hard-core Eclipse fans such as me (for over 20 years) are seriously considering throwing in the towel and moving to Visual Studio Code. (And when Eclipse comes along and breaks fundamental editing keystrokes such as in eclipse-platform/eclipse.platform.ui#513, it leaves fewer and fewer reasons to be loyal.)

**Comment by mickaelistria** [comment] 2023-03-21 19:01
Duplicate of #372

**Closed as completed by mickaelistria** 2023-03-21 19:01 UTC
